### PR TITLE
Variable Font Update

### PR DESCRIPTION
**Pull request by cosmicmocha**
Hi! Your glyphs file was perfectly set up to export as a variable font! All I did here was:
- Added the variable font parameters to the Montserrat Glyphs file
- Added ready to use variable font files to the fonts folder

Cheers,
Valery Marier :-)

### CODE REVIEW

**Comment by m4rc1e** [comment]
@cosmicmocha Thank you for the pull request!

Google Fonts and Type Network are currently converting popular families into variable fonts. So far we have around thirty families.

**Comment by pichotta** [comment]
Confirming this is the most current working data for Montserrat off of the 'fea-ufo-conv' branch
https://github.com/TypeNetwork/Montserrat/tree/fea-ufo-conv

**Comment by cosmicmocha** [comment]
Hello @m4rc1e! 

Feel free to review and work on this pr. 

I'm a student still so with my course work and search for internships my free time is limited. Plus, you and everyone at Type Network have much more experience with typeface design than I do. I feel like you can give this family the care and attention to detail that it deserves. 

I'm really excited to see/use the families that Type Network and Google Fonts are converting to variable fonts. As someone who loves both web design and typesetting, it makes me excited for the new possibilities that these fonts create for future of the web!  

Cheers,
Valery Marier

**Comment by alerque** [comment]
@JulietaUla What's the status on reviewing this and/or merging it? What would it be waiting on to merge and tag it v8.000 as indicated? If this is in working condition it would be lovely to tag it and be able to package/use it easily.

**Comment by Kulcanhez** [comment]
@JulietaUla any news on this? 😄 Thank you!!!!

**Comment by pichotta** [comment]
@Kulcanhez 

The most current VF font data can be found in this fork
https://github.com/TypeNetwork/Montserrat

cc: @JulietaUla

**Comment by Kulcanhez** [comment]
> @Kulcanhez
> 
> The most current VF font data can be found in this fork
> https://github.com/TypeNetwork/Montserrat
> 
> cc: @JulietaUla

Really thank you for your reply. What's missing to be in the master branch? 🙂

**Comment by JulietaUla** [comment]
Thank you for your valuable contribution!

**Pull request closed without merging**
