### PR TITLE
v7.200 gf mastering

### PR DESCRIPTION
**Pull request by m4rc1e**
Updated copyright string and Win Ascent

### CODE REVIEW

**Comment by juandelperal** [comment]
Thanks @m4rc1e !
I see only ttfs and otfs, webfonts will mantain untoched? Let me know if we are ready to add the tag. Thanks!

**Comment by m4rc1e** [comment]
@juandelperal sorry, I should've genned them as well. Can you add them please?

**Comment by juandelperal** [comment]
Yes, sure :)
Would it be ok to do it in Version 2.4.4 (1075)?

**Comment by m4rc1e** [comment]
That's what I used :-)

**Comment by davelab6** [comment]
has the overlap problem found in v2.4.4 exports been fixed manually?

**Pull request merged**
