### PR TITLE
v 9.0

### PR DESCRIPTION
**Pull request by juandelperal**
This version is a big update.

- We are introducing a new subfamily: Montserrat Underline, which is the new version and replacement of [Montserrat Subrayada](https://fonts.google.com/specimen/Montserrat+Subrayada) 
- Includes many African languages (SSA)
- Improvements for the building pipeline and testing.
- Many other improvements and character extension growth 2731 vs 1968 glyphs

### CODE REVIEW

**Comment by juandelperal** [comment]
Hi @m4rc1e 
After merging, I fixed some problems with the building pipeline and the config yamls (latests commits).
Still, after `make build` I find many files that shouldn't be there:

```
+sources/.ninja_log
+sources/build.ninja
+sources/instance_ufos/
```

Is there something wrong in the pipeline? should we .gititnore them?

**Comment by m4rc1e** [comment]
Looks like something wrong in gftools builder.

**Comment by kenmcd** [comment]
There is an issue in the static ThinItalic fonts affecting the uppercase `U`.
It appears to be broken.
And not all of the composites are the same.

Montserrat-ThinItalic.otf
Montserrat-ThinItalic.ttf
The VF Italic seems to be fine.

Maybe something in the build process is causing this.

Static ThinItalic U

Static ThinItalic U composites

**Comment by juandelperal** [comment]
Thanks @kenmcd will review it

**Comment by juandelperal** [comment]
We updated the first point of the shape in case that was the problem, but it didn't work
It seems though that it's related to gftools builder. Comparison:

**Built using gftools**
Screenshot 2024-10-17 at 10 55 22

**Exported directly from Glyphs**
Screenshot 2024-10-17 at 10 55 17

It only happens with U, not with similar shapes /W.ss01/U.ss01
Screenshot 2024-10-17 at 10 59 23


cc @m4rc1e

**Comment by m4rc1e** [comment]
@juandelperal got a fix. In the `config.yaml`, add the following `extraStaticFontmakeArgs: "--overlaps-backend pathops"`

Screenshot 2024-10-17 at 10 56 57

**Comment by juandelperal** [comment]
it worked! 
Now it should be fixed @kenmcd 

Thanks @m4rc1e

**Comment by m4rc1e** [comment]
Is there anything else we need to do in order to get this released? I think we're going to ignore the bracket layers and INDD issue for this release.

**Comment by juandelperal** [comment]
I added a known issues section to the readme mentioning these bugs.
Thanks a lot @m4rc1e

**Pull request merged**
