### PR TITLE
Armenian glyphs added

### PR DESCRIPTION
**Pull request by greghub**
please review and accept the Armenian glyphs for Montserrat. Contact for any issues
vahan.hovh@gmail.com (contributor)
greg.hovanesyan@gmail.com (me)

### CODE REVIEW

**Comment by CaroGiovagnoli** [comment]
Hi!
In a first view you have made a great work.
We have made some review of your work, here is pdf with some issues.
Any comment you have, please, let us know.
[Montserrat_armenia review 27-01.pdf](https://github.com/JulietaUla/Montserrat/files/735780/Montserrat_armenia.review.27-01.pdf)

**Comment by greghub** [comment]
Hi Carolina!
We've pushed the updates. there's a PDF explaining what have been updated (also attached here). If everything looks good, please let us know. thanks!
[pres.pdf](https://github.com/JulietaUla/Montserrat/files/740075/pres.pdf)

**Comment by davelab6** [comment]
@greghub please could you post a review request on https://groups.google.com/forum/#!topic/googlefonts-discuss/ so others could take a look, attaching all the PDFs from here? :)

**Comment by davelab6** [comment]
@greghub please join the discussion in https://groups.google.com/d/topic/googlefonts-discuss/JAWO9Jt8QdY/discussion :)

**Comment by vahanhovh** [comment]
pushed latest .glyphs file here as well

**Comment by saroyandavid** [comment]
Hi guys! Do you have any info when will be the Armenian characters pulled to the main type?

**Pull request closed without merging**
